version: '3'
services:
  consul:
    image: consul:1.8.4
    command: consul agent -dev -client 0.0.0.0
    ports:
      - "8500:8500"
      - "8600:8600/udp"
  customer:
    build: ../microservice-consul-demo/microservice-consul-demo-customer
    links:
     - consul
  catalog:
    build: ../microservice-consul-demo/microservice-consul-demo-catalog
    links:
     - consul
  order:
    build: ../microservice-consul-demo/microservice-consul-demo-order
    links:
     - consul
  apache:
    build: apache
    links:
     - consul
    depends_on:
     - consul
    ports:
     - "8080:80"
  prometheus:
    build: prometheus
    links:
     - order
    ports:
     - "9090:9090"