version: '3'
volumes:
  log:
services:
  consul:
    image: consul:1.8.4
    command: consul agent -dev -client 0.0.0.0
    ports:
      - "8500:8500"
      - "8600:8600/udp"
  customer:
    build: ../microservice-consul-demo/microservice-consul-demo-customer
    links:
     - consul
    volumes:
     - log:/log
  catalog:
    build: ../microservice-consul-demo/microservice-consul-demo-catalog
    links:
     - consul
    volumes:
     - log:/log
  order:
    build: ../microservice-consul-demo/microservice-consul-demo-order
    links:
     - consul
    volumes:
     - log:/log
  filebeat:
    build: filebeat
    volumes:
     - log:/log    
    links:
      - elasticsearch
  elasticsearch:
    build: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - discovery.type=single-node
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.1
    ports:
      - 5601:5601
    links:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
  apache:
    build: apache
    links:
     - consul
    depends_on:
     - consul
    ports:
     - "8080:80"