spring:
  application:
    name: hello-gemini
  ai:
    vertex:
      ai:
        gemini:
          project-id: hello-spring-ai
          location: us-central1
          chat:
            options:
              model: gemini-2.0-flash-001